name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private pac0kages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.11.0
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.1
  uuid: ^3.0.1
  provider: ^5.0.0
  date_format: ^2.0.2
  firebase_storage: ^8.0.0
  image_picker: ^0.7.3
  carousel_pro: ^1.0.0
  flutter_svg: ^0.21.0
  firebase_auth: ^1.0.1
  flutter_staggered_grid_view: ^0.4.0
  showcaseview: ^1.1.1
  expandable: ^5.0.1

  flutter_local_notifications: ^5.0.0
  firebase_messaging: ^9.1.3
  share: ^0.6.5+4
  cached_network_image: ^3.0.0
  chips_choice: ^2.0.1
  firebase_dynamic_links: ^0.8.0
  toast: ^0.1.5
  timeago: ^3.1.0
  shared_preferences:
  alert_dialog: ^0.2.0
  flutter_colored_progress_indicators: ^1.2.0
  connectivity: ^3.0.3
  flutter_offline: ^2.0.0
  data_connection_checker: ^0.3.4
  spinner_input: ^0.1.2
  flutter_material_color_picker: ^1.0.5
  google_sign_in: ^5.0.3
  smooth_star_rating: 1.1.1
  flutter_simple_rating_bar: 0.0.3

  geolocator: ^7.0.3
  geocoder: ^0.2.1
  geocoding:
  date_time_format: ^2.0.1
  custom_timer: ^0.0.6
  animated_text: ^1.0.2
  animated_text_kit: ^4.2.1
  animated_widgets: ^1.1.0
  animated_bottom_navigation_bar: ^0.3.2
  draggable_home: ^1.0.2
  firebase_picture_uploader: ^1.2.3
  awesome_dialog: ^2.1.0

  url_launcher:
  package_info:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SamRegular
      fonts:
        - asset: assets\fonts\Roboto-Regular.ttf
    - family: SamBold
      fonts:
        - asset: assets\fonts\Roboto-Bold.ttf
    - family: SamMedium
      fonts:
        - asset: assets\fonts\Roboto-Medium.ttf
    - family: SamLight
      fonts:
        - asset: assets\fonts\Roboto-Light.ttf
    - family: SamThin
      fonts:
        - asset: assets\fonts\Roboto-Thin.ttf
    - family: SamBoldItalic
      fonts:
        - asset: assets\fonts\Roboto-BoldItalic.ttf
    - family: SamItalic
      fonts:
        - asset: assets\fonts\Roboto-Italic.ttf
    - family: PopBold
      fonts:
        - asset: assets\fonts\Poppins-Bold.ttf
    - family: PopLight
      fonts:
        - asset: assets\fonts\Poppins-Light.ttf
    - family: PopSemi
      fonts:
        - asset: assets\fonts\Poppins-SemiBold.ttf
    - family: Monotype
      fonts:
        - asset: assets\fonts\911Fonts.com_MonotypeCorsiva_Regular_-_911fonts.com_fonts_gyWJ.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
